[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "15.5.1", RUBY_VERSION = "2.7.1" }

[context.deploy-preview]
  environment = { NODE_VERSION = "15.5.1", RUBY_VERSION = "2.7.1" }

[dev]
  command = "npm run dev"
  publish = "dist"
  targetPort = 3000
  port = 8080
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
